### ISSUE TITLE
Swift error

### ISSUE THREAD

**Issue by bradintheusa** [AppleEducate/get_version#2]
I tried using this but had all sorts of errors with swift plugins.   Then came across this

https://github.com/flutter/flutter/issues/16049

Any ideas.

**Comment by AppleEducate** [comment]
I have tried multiple things. what seems to work is deleting /Pods and /Podfile.lock and running pod install

**Comment by bradintheusa** [comment]
Tried that, didn't work.  I think I need to make a new project  and maybe it's an old project format that I have.
